"""Ruler timelines and traits for Colonial Simulator.
Pure static data extracted from index.py. index.py imports these names from here.
Format: _RULERS = {faction: [(start_year, end_year, image_path, name), ...]}
"""

_RULERS = {
    "Great Britain": [
        (1727, 1760, "images/rulers/georgeII.png", "King George II"),
        (1760, 1820, "images/rulers/georgeIII.png", "King George III"),
        (1820, 1830, "images/rulers/georgeIV.png", "King George IV"),
        (1830, 1837, "images/rulers/williamIV.png", "King William IV"),
        (1837, 1901, "images/rulers/victoria.png", "Queen Victoria"),
    ],
    "France": [
        (1715, 1774, "images/rulers/louisXV.png", "King Louis XV"),
        (1774, 1792, "images/rulers/louisXVI.png", "King Louis XVI"),
        (1792, 1804, "images/rulers/convention.png", "National Convention"),
        (1804, 1814, "images/rulers/napoleonI.png", "Emperor Napoleon I"),
        (1814, 1824, "images/rulers/louisXVIII.png", "King Louis XVIII"),
        (1824, 1830, "images/rulers/charlesx.png", "King Charles X"),
        (1830, 1848, "images/rulers/louis-philippeI.png", "King Louis-Philippe I"),
        (1852, 1870, "images/rulers/napoleonIII.png", "Emperor Napoleon III"),
    ],
    "Spain": [
        (1746, 1759, "images/rulers/ferdinandVI.png", "King Ferdinand VI"),
        (1759, 1788, "images/rulers/charlesIII.png", "King Charles III"),
        (1788, 1808, "images/rulers/charlesIV.png", "King Charles IV"),
        (1808, 1813, "images/rulers/josephI.png", "King Joseph I"),
        (1813, 1833, "images/rulers/ferdinandVII.png", "King Ferdinand VII"),
        (1833, 1868, "images/rulers/isabellaII.png", "Queen Isabella II"),
        (1870, 1873, "images/rulers/amadeoI.png", "King Amadeo I"),
        (1873, 1874, "images/rulers/convention.png", "First Republic"),
        (1886, 1931, "images/rulers/alfonsoXIII.png", "King Alfonso XIII"),
    ],
    "United States": [
        (1789, 1797, "images/rulers/georgewashington.jpg", "George Washington"),
        (1797, 1801, "images/rulers/johnadams.jpg", "John Adams"),
        (1801, 1809, "images/rulers/thomasjefferson.webp", "Thomas Jefferson"),
        (1809, 1817, "images/rulers/jamesmadison.jpg", "James Madison"),
        (1817, 1825, "images/rulers/jamesmonroe.jpg", "James Monroe"),
        (1825, 1829, "images/rulers/johnqadams.png", "John Q. Adams"),
        (1829, 1837, "images/rulers/andrewjackson.jpg", "Andrew Jackson"),
        (1837, 1841, "images/rulers/martinvanburen.png", "Martin Van Buren"),
        (1841, 1841, "images/rulers/williamhharrison.jpg", "William H. Harrison"),
        (1841, 1845, "images/rulers/johntyler.jpg", "John Tyler"),
        (1845, 1849, "images/rulers/jameskpolk.png", "James K. Polk"),
        (1849, 1850, "images/rulers/zacharytaylor.png", "Zachary Taylor"),
        (1850, 1853, "images/rulers/millardfillmore.png", "Millard Fillmore"),
        (1853, 1857, "images/rulers/franklinpierce.png", "Franklin Pierce"),
        (1857, 1861, "images/rulers/jamesbuchanan.jpg", "James Buchanan"),
        (1861, 1865, "images/rulers/abrahamlincoln.png", "Abraham Lincoln"),
        (1865, 1869, "images/rulers/andrewjohnson.png", "Andrew Johnson"),
        (1869, 1877, "images/rulers/ulyssessgrant.jpg", "Ulysses S. Grant"),
        (1877, 1881, "images/rulers/rutherfodbhayes.png", "Rutherford B. Hayes"),
        (1881, 1881, "images/rulers/jamesagarfield.png", "James A. Garfield"),
        (1881, 1885, "images/rulers/chesteraarthur.png", "Chester A. Arthur"),
        (1885, 1889, "images/rulers/grovercleveland.png", "Grover Cleveland"),
    ],
    "Mexico": [
        (1810, 1811, "images/rulers/miguelhidalgo.png", "Miguel Hidalgo"),
        (1811, 1813, "images/rulers/ignaciolópezrayón.png", "Ignacio Lopez Rayon"),
        (1813, 1821, "images/rulers/convention.png", "Independence War"),
        (1821, 1823, "images/rulers/agustinI.png", "Emperor Agustin I"),
        (1823, 1824, "images/rulers/convention.png", "Provisional Government"),
        (1824, 1829, "images/rulers/guadalupevictoria.png", "Guadalupe Victoria"),
        (1829, 1829, "images/rulers/vicenteguerrero.png", "Vicente Guerrero"),
        (1829, 1832, "images/rulers/anastasiobustamante.png", "Anastasio Bustamante"),
        (1832, 1833, "images/rulers/manuelgómezpedraza.png", "Manuel Gomez Pedraza"),
        (1833, 1835, "images/rulers/antoniolópezdesantaanna.png", "Santa Anna"),
        (1835, 1836, "images/rulers/miguelbarragán.png", "Miguel Barragan"),
        (1836, 1837, "images/rulers/josejustocorro.png", "Jose Justo Corro"),
        (1837, 1841, "images/rulers/anastasiobustamante.png", "Anastasio Bustamante"),
        (1841, 1844, "images/rulers/antoniolópezdesantaanna.png", "Santa Anna"),
        (1844, 1847, "images/rulers/joséjoaquíndeHerrera.jpg", "Jose J. de Herrera"),
        (1847, 1848, "images/rulers/antoniolópezdesantaanna.png", "Santa Anna"),
        (1848, 1848, "images/rulers/pedromaríaanaya.jpg", "Pedro Maria Anaya"),
        (1848, 1849, "images/rulers/manueldelapeñaypeña.jpg", "Manuel de la Pena"),
        (1849, 1851, "images/rulers/joséjoaquíndeHerrera.jpg", "Jose J. de Herrera"),
        (1851, 1853, "images/rulers/marianoarista.png", "Mariano Arista"),
        (1853, 1855, "images/rulers/antoniolópezdesantaanna.png", "Santa Anna"),
        (1855, 1855, "images/rulers/juanalvarez.jpg", "Juan Alvarez"),
        (1855, 1857, "images/rulers/ignaciocomonfort.png", "Ignacio Comonfort"),
        (1857, 1861, "images/rulers/miguelmiramón.png", "Miguel Miramon"),
        (1858, 1872, "images/rulers/benitojuárez.jpg", "Benito Juarez"),
        (1864, 1867, "images/rulers/maximilianI.png", "Emperor Maximilian I"),
        (1872, 1876, "images/rulers/sebastiánlerdodetejada.png", "Sebastian Lerdo de Tejada"),
        (1876, 1876, "images/rulers/juanméndez.png", "Juan N. Mendez"),
        (1876, 1880, "images/rulers/porfiriodíaz.png", "Porfirio Diaz"),
        (1880, 1884, "images/rulers/manuelgonzález.png", "Manuel Gonzalez"),
        (1884, 1911, "images/rulers/porfiriodíaz.png", "Porfirio Diaz"),
    ],
    "Haiti": [
        (1804, 1806, "images/rulers/jeanjacquesdessalines.jpg", "Emperor Jacques I"),
        (1806, 1807, "images/rulers/convention.png", "Provisional Government"),
        (1807, 1818, "images/rulers/alexandrepétion.png", "Alexandre Petion"),
        (1811, 1820, "images/rulers/henriI.jpg", "King Henri I"),
        (1818, 1843, "images/rulers/jeanpierreboyer.png", "Jean-Pierre Boyer"),
        (1843, 1844, "images/rulers/charlesrivièrehérard.png", "Charles Riviere-Herard"),
        (1844, 1845, "images/rulers/philippeguerrier.png", "Philippe Guerrier"),
        (1845, 1846, "images/rulers/jeanlouispierrot.png", "Jean-Louis Pierrot"),
        (1846, 1847, "images/rulers/jeanbaptisteriché.jpg", "Jean-Baptiste Riche"),
        (1847, 1849, "images/rulers/faustinI.png", "Emperor Faustin I"),
        (1849, 1859, "images/rulers/faustinI.png", "Emperor Faustin I"),
        (1859, 1867, "images/rulers/fabregeffrard.png", "Fabre Geffrard"),
        (1867, 1869, "images/rulers/sylvainsalnave.png", "Sylvain Salnave"),
        (1869, 1870, "images/rulers/convention.png", "Provisional Government"),
        (1870, 1874, "images/rulers/nissagesaget.png", "Nissage Saget"),
        (1874, 1876, "images/rulers/micheldomingue.png", "Michel Domingue"),
        (1876, 1879, "images/rulers/pierrethéomaboisrondcanal.png", "Boisrond-Canal"),
        (1879, 1888, "images/rulers/lysiussalomon.png", "Lysius Salomon"),
        (1888, 1889, "images/rulers/convention.png", "Provisional Government"),
        (1889, 1896, "images/rulers/florvilhyppolite.png", "Florvil Hyppolite"),
        (1896, 1902, "images/rulers/tirésiassimonsam.png", "Tiresias Simon Sam"),
        (1902, 1908, "images/rulers/pierrenordalexis.png", "Pierre Nord Alexis"),
        (1908, 1911, "images/rulers/françoisdenyslégitime.png", "Francois D. Legitime"),
    ],
    "Denmark": [
        (1746, 1766, "images/rulers/frederickV.png", "King Frederick V"),
        (1766, 1808, "images/rulers/christianVII.png", "King Christian VII"),
        (1808, 1839, "images/rulers/frederickVI.jpg", "King Frederick VI"),
        (1839, 1848, "images/rulers/christianVIII.png", "King Christian VIII"),
        (1848, 1863, "images/rulers/frederickVII.jpg", "King Frederick VII"),
        (1863, 1906, "images/rulers/christianIX.png", "King Christian IX"),
    ],
    "Russia": [
        (1741, 1762, "images/rulers/elizabeth.jpg", "Empress Elizabeth"),
        (1762, 1762, "images/rulers/peterIII.png", "Emperor Peter III"),
        (1762, 1796, "images/rulers/catherineII.png", "Empress Catherine II"),
        (1796, 1801, "images/rulers/paulI.png", "Emperor Paul I"),
        (1801, 1825, "images/rulers/alexanderI.png", "Emperor Alexander I"),
        (1825, 1855, "images/rulers/nicholasI.jpg", "Emperor Nicholas I"),
        (1855, 1881, "images/rulers/alexanderII.webp", "Emperor Alexander II"),
        (1881, 1894, "images/rulers/alexanderIII.jpg", "Emperor Alexander III"),
        (1894, 1917, "images/rulers/nicholasII.avif", "Emperor Nicholas II"),
    ],
}


_RULER_TRAITS = {
    # Great Britain
    "King George II": ["Militarist", "Defensive"],
    "King George III": ["Mad", "Imperialist", "Pious"],
    "King George IV": ["Lavish", "Spendthrift", "Unpopular"],
    "King William IV": ["Reformer", "Pacifist"],
    "Queen Victoria": ["Imperialist", "Industrialist", "Beloved"],
    # France
    "King Louis XV": ["Lavish", "Weak", "Patron of Trade"],
    "King Louis XVI": ["Weak", "Unpopular", "Reformer"],
    "National Convention": ["Conqueror", "Tyrant", "Reformer"],
    "Emperor Napoleon I": ["Conqueror", "Militarist", "Mercantilist"],
    "King Louis XVIII": ["Pacifist", "Aged", "Diplomat"],
    "King Charles X": ["Pious", "Unpopular", "Imperialist"],
    "King Louis-Philippe I": ["Mercantilist", "Patron of Trade", "Reformer"],
    "Emperor Napoleon III": ["Expansionist", "Industrialist", "Militarist"],
    # Spain
    "King Ferdinand VI": ["Pacifist", "Mercantilist", "Pious"],
    "King Charles III": ["Enlightened", "Reformer", "Industrialist"],
    "King Charles IV": ["Weak", "Spendthrift", "Lavish"],
    "King Joseph I": ["Unpopular", "Weak", "Reformer"],
    "King Ferdinand VII": ["Tyrant", "Pious", "Unpopular"],
    "Queen Isabella II": ["Lavish", "Unpopular", "Pious"],
    "King Amadeo I": ["Reformer", "Unpopular", "Young"],
    "First Republic": ["Reformer", "Weak"],
    "King Alfonso XIII": ["Militarist", "Spendthrift", "Young"],
    # United States
    "George Washington": ["Defensive", "Beloved", "Diplomat"],
    "John Adams": ["Diplomat", "Pacifist"],
    "Thomas Jefferson": ["Enlightened", "Expansionist", "Reformer"],
    "James Madison": ["Militarist", "Weak"],
    "James Monroe": ["Expansionist", "Diplomat", "Pacifist"],
    "John Q. Adams": ["Diplomat", "Aged"],
    "Andrew Jackson": ["Conqueror", "Imperialist", "Tyrant"],
    "Martin Van Buren": ["Spendthrift", "Unpopular"],
    "William H. Harrison": ["Militarist", "Young"],
    "John Tyler": ["Isolationist", "Unpopular"],
    "James K. Polk": ["Expansionist", "Imperialist", "Industrialist"],
    "Zachary Taylor": ["Militarist", "Defensive"],
    "Millard Fillmore": ["Pacifist", "Weak"],
    "Franklin Pierce": ["Spendthrift", "Unpopular", "Weak"],
    "James Buchanan": ["Weak", "Unpopular", "Aged"],
    "Abraham Lincoln": ["Reformer", "Beloved", "Conqueror"],
    "Andrew Johnson": ["Unpopular", "Weak"],
    "Ulysses S. Grant": ["Conqueror", "Militarist", "Spendthrift"],
    "Rutherford B. Hayes": ["Reformer", "Pacifist"],
    "James A. Garfield": ["Reformer", "Young"],
    "Chester A. Arthur": ["Reformer", "Mercantilist"],
    "Grover Cleveland": ["Mercantilist", "Pacifist", "Reformer"],
    # Mexico
    "Miguel Hidalgo": ["Conqueror", "Beloved", "Reformer"],
    "Ignacio Lopez Rayon": ["Militarist", "Reformer"],
    "Independence War": ["Conqueror", "Reformer"],
    "Emperor Agustin I": ["Imperialist", "Lavish", "Unpopular"],
    "Guadalupe Victoria": ["Beloved", "Defensive", "Reformer"],
    "Vicente Guerrero": ["Conqueror", "Reformer", "Beloved"],
    "Anastasio Bustamante": ["Militarist", "Tyrant"],
    "Manuel Gomez Pedraza": ["Pacifist", "Weak"],
    "Santa Anna": ["Conqueror", "Spendthrift", "Tyrant"],
    "Miguel Barragan": ["Defensive", "Aged"],
    "Jose Justo Corro": ["Pious", "Weak"],
    "Jose J. de Herrera": ["Pacifist", "Diplomat", "Reformer"],
    "Pedro Maria Anaya": ["Defensive", "Militarist"],
    "Manuel de la Pena": ["Pacifist", "Weak"],
    "Mariano Arista": ["Militarist", "Unpopular"],
    "Juan Alvarez": ["Reformer", "Conqueror"],
    "Ignacio Comonfort": ["Reformer", "Weak"],
    "Miguel Miramon": ["Militarist", "Young", "Tyrant"],
    "Benito Juarez": ["Reformer", "Beloved", "Enlightened"],
    "Emperor Maximilian I": ["Enlightened", "Unpopular", "Lavish"],
    "Sebastian Lerdo de Tejada": ["Reformer", "Diplomat"],
    "Juan N. Mendez": ["Militarist", "Young"],
    "Porfirio Diaz": ["Tyrant", "Industrialist", "Mercantilist"],
    "Manuel Gonzalez": ["Spendthrift", "Militarist"],
    # Haiti
    "Emperor Jacques I": ["Conqueror", "Tyrant", "Militarist"],
    "Alexandre Petion": ["Reformer", "Beloved", "Diplomat"],
    "King Henri I": ["Tyrant", "Industrialist", "Defensive"],
    "Jean-Pierre Boyer": ["Diplomat", "Expansionist", "Mercantilist"],
    "Charles Riviere-Herard": ["Militarist", "Unpopular"],
    "Philippe Guerrier": ["Aged", "Militarist"],
    "Jean-Louis Pierrot": ["Militarist", "Unpopular"],
    "Jean-Baptiste Riche": ["Aged", "Weak"],
    "Emperor Faustin I": ["Tyrant", "Lavish", "Spendthrift"],
    "Fabre Geffrard": ["Reformer", "Enlightened", "Diplomat"],
    "Sylvain Salnave": ["Militarist", "Unpopular", "Conqueror"],
    "Nissage Saget": ["Pacifist", "Reformer"],
    "Michel Domingue": ["Tyrant", "Spendthrift"],
    "Boisrond-Canal": ["Pacifist", "Weak"],
    "Lysius Salomon": ["Reformer", "Industrialist", "Unpopular"],
    "Florvil Hyppolite": ["Industrialist", "Militarist"],
    "Tiresias Simon Sam": ["Spendthrift", "Weak"],
    "Pierre Nord Alexis": ["Tyrant", "Militarist", "Aged"],
    "Francois D. Legitime": ["Diplomat", "Weak"],
    # Denmark
    "King Frederick V": ["Patron of Trade", "Lavish", "Pacifist"],
    "King Christian VII": ["Mad", "Weak"],
    "King Frederick VI": ["Reformer", "Pacifist", "Mercantilist"],
    "King Christian VIII": ["Reformer", "Enlightened"],
    "King Frederick VII": ["Reformer", "Beloved", "Pacifist"],
    "King Christian IX": ["Diplomat", "Defensive", "Aged"],
    # Russia
    "Empress Elizabeth": ["Lavish", "Patron of Trade", "Diplomat"],
    "Emperor Peter III": ["Weak", "Unpopular"],
    "Empress Catherine II": ["Enlightened", "Expansionist", "Conqueror"],
    "Emperor Paul I": ["Tyrant", "Mad", "Militarist"],
    "Emperor Alexander I": ["Diplomat", "Reformer", "Conqueror"],
    "Emperor Nicholas I": ["Tyrant", "Defensive", "Militarist"],
    "Emperor Alexander II": ["Reformer", "Enlightened", "Expansionist"],
    "Emperor Alexander III": ["Isolationist", "Industrialist", "Tyrant"],
    "Emperor Nicholas II": ["Weak", "Unpopular", "Aged"],
}

